name: CD
on:
  release:
    types: published
jobs:
  docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.PAT }}
        config: .github/jazzy.yml
        version: ${{ github.event.release.tag_name }}
        history: false

  pods:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        VERSION: ${{ github.event.release.tag_name }}
